### ISSUE TITLE
Corrigir a query de busca

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#13]
Por algum motivo (creio que seja a forma que a query do mongo esteja sendo feita), quando procuramos por uma palavra pela metade, não damos um match em nenhuma oferta no banco. 

Exemplo: Buscar pela letra A.
Resultado Obtido: Nenhuma oferta encontrada.
Resultado Esperado: Encontrar todas as ofertas que tenham A no título.

**Comment by DantasB** [comment]
https://stackoverflow.com/questions/44833817/mongodb-full-and-partial-text-search

**Comment by rpalmeira51** [comment]
Acho que não vale a pena fazer uma solução meio improvisada assim. Vale a pena ver depois com elastic search, REGEX é computacionalmente muito caro
