### ISSUE TITLE
Bug cadastro de usuário

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#27]
Atualmente o email e o CPF são únicas no banco de dados. Porém, mesmo que o usuário não esteja validado, essas informações ainda serão únicas. Deste modo eu posso botar o email de todos os professores e impedir que eles se cadastrem mesmo se eu não validar o usuário.

**Comment by rpalmeira51** [comment]
Na maioria dos sites funciona assim, não vejo muita solução. Acho que nesse inicio a gente pode resolver caso a caso. Se for muito necessário, podemos tentar fazer um ip não poder criar várias contas, mas isso pode gerar problemas também

**Comment by DantasB** [comment]
O Projeto do user_cleaner resolve esse problema!
