### ISSUE TITLE
Criar um processo para apagar contas inválidas acima de 7 dias

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#31]
Atualmente, após criar uma conta, se ela permanecer inválida, ela ficará no nosso banco indeterminadamente. Para tal, vale criar um processo secundário para apagar os dados do banco com mais de 7 dias da data de criação e que não esteja ativada.

**Comment by rpalmeira51** [comment]
Complicado fazer por causa do docker. Geralmente isso seria um CROWN JOB. Talvez fazer outro serviço ? Mas será complicadinho
