### ISSUE TITLE
Editar campos do usuário

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#32]
- Adicionar data de cadastro.
- Adicionar campo de faculdade. (Como pretendemos expandir horizontes, ter esse campo vai nos ajudar futuramente).
- Remover campo de CPF. Atualmente não há necessidade de termos este campo.

**Comment by rpalmeira51** [comment]
Vale a pena mesmo remover CPF ? Só discordo um pouco disso, mas isso dá para implementar
