### ISSUE TITLE
Adicionar possibilidade de adicionar imagem

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#35]
É sabido que algumas empresas possuem o costume de criar imagens para divulgar suas ofertas. Se a gente tivesse um campo para aceitar essas imagens a gente facilitaria a experiência do usuário.

**Comment by rpalmeira51** [comment]
Precisa combinar isso com o front essa interação. Seria arquivo ? Base 64 ? Mas dá para fazer
