### ISSUE TITLE
Olhar o code climate e fazer as modificações sugeridas

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#36]

**Comment by rpalmeira51** [comment]
A maioria das modificações são do código email que vale a pena mudar. O resto é a seed que é para ser repetido mesmo, algumas coisas que ele fala que é difícil, mas é tranquilo e algumas repetições de tratamento de null nas promisses que é duas linhas. Não acho que valha mudar isso. Acho melhor essas ferramentas como guia para gente reavaliar e não para guiar a gente
