### ISSUE TITLE
Adicionar um sistema de mensageria (RabbitMQ) 

### ISSUE THREAD

**Issue by DantasB** [CorchoForce/pav-back#37]
Atualmente o sistema de envio de emails pode acabar gargalando todo o processo. 

É interessante integrar o nodemailer com o RabbitMQ (ou alternativas) para tratarmos esse envio em processos externos.

**Comment by rpalmeira51** [comment]
Acho não precisa não. Dá para só fazer um serviço e mandar como http, não sei se node é o ideal, pois pode ter um processamento em cima do email. Dá para fazer esse serviço em go ou php
